# This workflow will run commands in a container on multiple jobs

name: matrix-container

on:
  workflow_dispatch:

jobs:
  workflow-test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        bins: [ "/bin/ls", "/bin/bash", "/bin/grep" ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run command in devcontainer
      uses: devcontainers/ci@v0.3
      with:
        cacheFrom: ghcr.io/clearbluejar/ghidrecomp
        push: never
        runCmd: |
          pip install ghidrecomp
          ghdirecomp ${{ matrix.bins }}
