# This workflow will run commands in a container on multiple jobs

name: matrix-container

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:

  workflow-test:

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/clearbluejar/ghidrecomp:latest
      env:
        GHIDRA_INSTALL_DIR: "/ghidra"
      options: --user vscode

    strategy:
      fail-fast: false
      matrix:
        bins: [ "/bin/ls", "/bin/bash", "/bin/grep" ]
    steps:
    - uses: actions/checkout@v3    
    - name: Run command in image
      run: |        
        python3 -m venv .env
        source .env/bin/activate
        pip install ghidrecomp
        cd /tmp
        ghidrecomp ${{ matrix.bins }}
      shell: bash
    - name: Upload decompilations
      uses: actions/upload-artifact@v3
      with:
        name: decompilations
        path: decompilations
