# This workflow will run commands in a container on multiple jobs

name: matrix-container

on:
  workflow_dispatch:

jobs:

  workflow-test:

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/clearbluejar/ghidrecomp:latest
    strategy:
      fail-fast: false
      matrix:
        bins: [ "/bin/ls", "/bin/bash", "/bin/grep" ]
    steps:
    - uses: actions/checkout@v3    
    - name: Run command in image
      run: |
        pip install ghidrecomp
        ghdirecomp ${{ matrix.bins }}
